# Form implementation generated from reading ui file 'VentanaReservar.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_VentanaReservar(object):
    def setupUi(self, VentanaReservar):
        VentanaReservar.setObjectName("VentanaReservar")
        VentanaReservar.resize(1126, 682)
        VentanaReservar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lblTitulo = QtWidgets.QLabel(parent=VentanaReservar)
        self.lblTitulo.setGeometry(QtCore.QRect(600, 10, 201, 31))
        self.lblTitulo.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgba(64, 182, 200, 0)")
        self.lblTitulo.setObjectName("lblTitulo")
        self.lblReferencia = QtWidgets.QLabel(parent=VentanaReservar)
        self.lblReferencia.setGeometry(QtCore.QRect(0, 0, 331, 711))
        self.lblReferencia.setText("")
        self.lblReferencia.setPixmap(QtGui.QPixmap("Vista/Imagenes/fondoRestaurante.jpg"))
        self.lblReferencia.setScaledContents(False)
        self.lblReferencia.setObjectName("lblReferencia")
        self.lblNumre = QtWidgets.QLabel(parent=VentanaReservar)
        self.lblNumre.setGeometry(QtCore.QRect(340, 60, 161, 21))
        self.lblNumre.setObjectName("lblNumre")
        self.txtNumeroReserva = QtWidgets.QLineEdit(parent=VentanaReservar)
        self.txtNumeroReserva.setGeometry(QtCore.QRect(510, 60, 401, 22))
        self.txtNumeroReserva.setObjectName("txtNumeroReserva")
        self.lblHora = QtWidgets.QLabel(parent=VentanaReservar)
        self.lblHora.setGeometry(QtCore.QRect(340, 410, 61, 21))
        self.lblHora.setObjectName("lblHora")
        self.lblFecha = QtWidgets.QLabel(parent=VentanaReservar)
        self.lblFecha.setGeometry(QtCore.QRect(340, 100, 61, 21))
        self.lblFecha.setObjectName("lblFecha")
        self.calendarioWFecha = QtWidgets.QCalendarWidget(parent=VentanaReservar)
        self.calendarioWFecha.setGeometry(QtCore.QRect(510, 100, 401, 236))
        self.calendarioWFecha.setObjectName("calendarioWFecha")
        self.btnGuardar = QtWidgets.QPushButton(parent=VentanaReservar)
        self.btnGuardar.setGeometry(QtCore.QRect(550, 610, 93, 28))
        self.btnGuardar.setObjectName("btnGuardar")
        self.btnCancelar = QtWidgets.QPushButton(parent=VentanaReservar)
        self.btnCancelar.setGeometry(QtCore.QRect(770, 610, 93, 28))
        self.btnCancelar.setObjectName("btnCancelar")
        self.tableHora = QtWidgets.QTableWidget(parent=VentanaReservar)
        self.tableHora.setGeometry(QtCore.QRect(510, 400, 270, 192))
        self.tableHora.setObjectName("tableHora")
        self.tableHora.setColumnCount(2)
        self.tableHora.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableHora.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableHora.setHorizontalHeaderItem(1, item)
        self.btnRegresar = QtWidgets.QPushButton(parent=VentanaReservar)
        self.btnRegresar.setGeometry(QtCore.QRect(1030, 600, 81, 61))
        self.btnRegresar.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Vista/Imagenes/atras.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnRegresar.setIcon(icon)
        self.btnRegresar.setIconSize(QtCore.QSize(50, 50))
        self.btnRegresar.setObjectName("btnRegresar")

        self.lblFecha_2 = QtWidgets.QLabel(parent=VentanaReservar)
        self.lblFecha_2.setGeometry(QtCore.QRect(340, 350, 61, 21))
        self.lblFecha_2.setObjectName("lblFecha_2")
        self.cbxMesas = QtWidgets.QComboBox(parent=VentanaReservar)
        self.cbxMesas.setGeometry(QtCore.QRect(510, 350, 391, 22))
        self.cbxMesas.setObjectName("cbxMesas")

        self.retranslateUi(VentanaReservar)
        QtCore.QMetaObject.connectSlotsByName(VentanaReservar)

    def retranslateUi(self, VentanaReservar):
        _translate = QtCore.QCoreApplication.translate
        VentanaReservar.setWindowTitle(_translate("VentanaReservar", "Resevar Mesa"))
        self.lblTitulo.setText(_translate("VentanaReservar", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">Reservar Mesa</span></p></body></html>"))
        self.lblNumre.setText(_translate("VentanaReservar", "<html><head/><body><p><span style=\" font-size:11pt;\">Numero de reserva:</span></p></body></html>"))
        self.lblHora.setText(_translate("VentanaReservar", "<html><head/><body><p><span style=\" font-size:11pt;\">Hora:</span></p></body></html>"))
        self.lblFecha.setText(_translate("VentanaReservar", "<html><head/><body><p><span style=\" font-size:11pt;\">Fecha:</span></p></body></html>"))
        self.btnGuardar.setText(_translate("VentanaReservar", "Guardar"))
        self.btnCancelar.setText(_translate("VentanaReservar", "Cancelar"))
        item = self.tableHora.horizontalHeaderItem(0)
        item.setText(_translate("VentanaReservar", "Hora"))
        item = self.tableHora.horizontalHeaderItem(1)
        item.setText(_translate("VentanaReservar", "Disponibilidad"))
        self.lblFecha_2.setText(_translate("VentanaReservar", "<html><head/><body><p><span style=\" font-size:11pt;\">Mesa:</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VentanaReservar = QtWidgets.QWidget()
    ui = Ui_VentanaReservar()
    ui.setupUi(VentanaReservar)
    VentanaReservar.show()
    sys.exit(app.exec())
