# Form implementation generated from reading ui file 'VentanaReportes.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1134, 590)
        Form.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lblTitulo = QtWidgets.QLabel(parent=Form)
        self.lblTitulo.setGeometry(QtCore.QRect(460, 0, 201, 31))
        self.lblTitulo.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgba(64, 182, 200, 0)")
        self.lblTitulo.setObjectName("lblTitulo")
        self.btnreporte1 = QtWidgets.QPushButton(parent=Form)
        self.btnreporte1.setGeometry(QtCore.QRect(45, 60, 91, 21))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Vista/Imagenes/buscar.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnreporte1.setIcon(icon)
        self.btnreporte1.setObjectName("btnreporte1")
        self.tablareporte1 = QtWidgets.QTableWidget(parent=Form)
        self.tablareporte1.setGeometry(QtCore.QRect(45, 100, 271, 281))
        self.tablareporte1.setObjectName("tablareporte1")
        self.tablareporte1.setColumnCount(0)
        self.tablareporte1.setRowCount(0)
        self.btnRegresar = QtWidgets.QPushButton(parent=Form)
        self.btnRegresar.setGeometry(QtCore.QRect(980, 450, 81, 61))
        self.btnRegresar.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Vista/Imagenes/atras.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnRegresar.setIcon(icon1)
        self.btnRegresar.setIconSize(QtCore.QSize(50, 50))
        self.btnRegresar.setObjectName("btnRegresar")
        self.btnreporte2 = QtWidgets.QPushButton(parent=Form)
        self.btnreporte2.setGeometry(QtCore.QRect(380, 60, 91, 21))
        self.btnreporte2.setIcon(icon)
        self.btnreporte2.setObjectName("btnreporte2")
        self.tablareporte2 = QtWidgets.QTableWidget(parent=Form)
        self.tablareporte2.setGeometry(QtCore.QRect(380, 100, 271, 281))
        self.tablareporte2.setObjectName("tablareporte2")
        self.tablareporte2.setColumnCount(0)
        self.tablareporte2.setRowCount(0)
        self.btnreporte3 = QtWidgets.QPushButton(parent=Form)
        self.btnreporte3.setGeometry(QtCore.QRect(720, 60, 91, 21))
        self.btnreporte3.setIcon(icon)
        self.btnreporte3.setObjectName("btnreporte3")
        self.tablareporte3 = QtWidgets.QTableWidget(parent=Form)
        self.tablareporte3.setGeometry(QtCore.QRect(720, 100, 271, 281))
        self.tablareporte3.setObjectName("tablareporte3")
        self.tablareporte3.setColumnCount(0)
        self.tablareporte3.setRowCount(0)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lblTitulo.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">Reportes</span></p><p align=\"center\"><br/></p></body></html>"))
        self.btnreporte1.setText(_translate("Form", "Reporte 1"))
        self.btnreporte2.setText(_translate("Form", "Reporte 2"))
        self.btnreporte3.setText(_translate("Form", "Reporte 3"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
