# Form implementation generated from reading ui file 'VentanaAcercade.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_VentanaAcercade(object):
    def setupUi(self, VentanaAcercade):
        VentanaAcercade.setObjectName("VentanaAcercade")
        VentanaAcercade.resize(1130, 711)
        VentanaAcercade.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lblnfo = QtWidgets.QLabel(parent=VentanaAcercade)
        self.lblnfo.setGeometry(QtCore.QRect(100, 40, 611, 481))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.lblnfo.setFont(font)
        self.lblnfo.setObjectName("lblnfo")
        self.lblFondo = QtWidgets.QLabel(parent=VentanaAcercade)
        self.lblFondo.setGeometry(QtCore.QRect(590, 20, 520, 750))
        self.lblFondo.setText("")
        self.lblFondo.setPixmap(QtGui.QPixmap("Vista/Imagenes/f.jpg"))
        self.lblFondo.setScaledContents(True)
        self.lblFondo.setObjectName("lblFondo")
        self.btnRegresar = QtWidgets.QPushButton(parent=VentanaAcercade)
        self.btnRegresar.setGeometry(QtCore.QRect(1020, 630, 81, 61))
        self.btnRegresar.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.btnRegresar.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Vista/Imagenes/atras.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnRegresar.setIcon(icon)
        self.btnRegresar.setIconSize(QtCore.QSize(50, 50))
        self.btnRegresar.setObjectName("btnRegresar")

        self.retranslateUi(VentanaAcercade)
        QtCore.QMetaObject.connectSlotsByName(VentanaAcercade)

    def retranslateUi(self, VentanaAcercade):
        _translate = QtCore.QCoreApplication.translate
        VentanaAcercade.setWindowTitle(_translate("VentanaAcercade", "Informacion"))
        self.lblnfo.setText(_translate("VentanaAcercade",
                                       "<html><head/><body><p>Restaurante BALCON CUENCANO</p>"
                                       "<p>Sistema de Reservas v1.0.0</p>"
                                       "<p>Descripción:</p>"
                                       "<p>Aplicacion de escritorio, para Resevar mesas en un restaurante</p>"
                                       "<p>Desarrolladores:</p><p>- Darwin Chuqui</p>"
                                       "<p>Créditos:</p><p>- https://www.flaticon.es/</p>"
                                       "<p>Notas de la Versión:</p><p>v1.0.0 (Fecha de lanzamiento: 23 de junio de 2024)</p>"
                                       "<p>-Correciones a futuro</p>"
                                       "<p>Contacto:</p>"
                                       "<p>Para asistencia y comentarios, contáctenos en support@helpreport.com</p>"
                                       "<p>¡Gracias por su atencion!</p><p><br/></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VentanaAcercade = QtWidgets.QWidget()
    ui = Ui_VentanaAcercade()
    ui.setupUi(VentanaAcercade)
    VentanaAcercade.show()
    sys.exit(app.exec())
